server:
  port: 8088

logging:
  level:
   org.springframework: DEBUG #config for log :  leave log the package inclue:org.springframework

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

  messages:
    basename: messages # to apply mulit-anguage



  #spring security 접속시 아이디비번을 직접 지정
  #security:
    #user:
     #name: username
      #password: 123

#actuator 포멧 수정
management:
  endpoints:
    web:
      exposure:
        include: "*"



